"""add interest_rate and pending_amount

Revision ID: 11559f5037ef
Revises: 
Create Date: 2025-09-29 14:18:49.141644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11559f5037ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interest_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pending_amount', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('pending_amount')
        batch_op.drop_column('interest_rate')

    # ### end Alembic commands ###
